<template>
  <div class="h-full flex flex-col">
    <!-- Header -->
    <div class="p-6 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center">
      <div>
        <h3 class="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
            Agent Facts
        </h3>
        <p class="text-xs text-gray-400 mt-1">Insights generated by your agents.</p>
      </div>
      <button 
        @click="fetchFacts" 
        class="text-sm text-gray-500 hover:text-black dark:text-gray-400 dark:hover:text-white font-medium flex items-center gap-1"
        :disabled="loading"
      >
        <svg v-if="loading" class="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
        Refresh
      </button>
    </div>

    <!-- Empty State -->
    <div v-if="!loading && facts.length === 0" class="flex-1 flex flex-col items-center justify-center p-8 text-gray-400">
         <svg class="w-12 h-12 mb-3 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
         <p>No agent facts found.</p>
    </div>

    <!-- List -->
    <div v-else class="flex-1 overflow-y-auto custom-scrollbar">
       <div v-if="loading && !facts.length" class="p-8 text-center text-gray-400">Loading...</div>
       <ul v-else class="divide-y divide-gray-100 dark:divide-gray-700">
         <li v-for="fact in paginatedFacts" :key="fact.id" class="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors duration-150 group">
           <div class="px-6 py-4 flex items-center justify-between cursor-pointer" @click="viewFact(fact)">
             <div class="flex-1 min-w-0 pr-4">
                <div class="flex items-center gap-2 mb-0.5">
                    <span class="text-[10px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/30 px-1.5 py-0.5 rounded">
                        {{ formatTag(fact) }}
                    </span>
                    <span class="text-[10px] text-gray-400">{{ formatDate(fact.created_at) }}</span>
                </div>
               <p class="text-sm text-gray-600 dark:text-gray-300 truncate mt-1 line-clamp-2">
                 {{ fact.content }}
               </p>
             </div>
             <div>
                <button class="text-gray-300 group-hover:text-black dark:text-gray-600 dark:group-hover:text-white p-1 rounded hover:bg-gray-100 dark:hover:bg-gray-700 transition-all">
                     <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" /></svg>
                </button>
             </div>
           </div>
         </li>
       </ul>
    </div>
    
    <!-- Pagination -->
    <div v-if="facts.length > 0" class="p-4 border-t border-gray-100 dark:border-gray-700 flex items-center justify-between bg-white dark:bg-surface">
        <span class="text-sm text-gray-500 dark:text-gray-400">
            Page {{ currentPage }} of {{ totalPages }}
        </span>
        <div class="flex gap-2">
            <button 
                @click="currentPage--" 
                :disabled="currentPage === 1"
                class="px-3 py-1 text-sm rounded bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
                Previous
            </button>
            <button 
                @click="currentPage++" 
                :disabled="currentPage === totalPages"
                class="px-3 py-1 text-sm rounded bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
                Next
            </button>
        </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import api from '../services/api';

const router = useRouter();
const facts = ref([]);
const loading = ref(false);
const currentPage = ref(1);
const itemsPerPage = 5;

const totalPages = computed(() => {
    return Math.ceil(facts.value.length / itemsPerPage);
});

const paginatedFacts = computed(() => {
    const start = (currentPage.value - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    return facts.value.slice(start, end);
});

const fetchFacts = async () => {
  loading.value = true;
  try {
    const response = await api.get('/memory/agent-facts');
    facts.value = response.data;
  } catch (error) {
    console.error('Failed to fetch agent facts:', error);
  } finally {
    loading.value = false;
  }
};

const viewFact = (fact) => {
  router.push(`/editor/${fact.id}`);
};

const formatDate = (dateStr) => {
  if (!dateStr) return '';
  const date = new Date(dateStr);
  return date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
};

const formatTag = (fact) => {
  if (fact.tags && fact.tags.includes('auto-fact')) return 'Auto Fact';
  return 'Agent Note';
};

onMounted(fetchFacts);
</script>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 4px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: rgba(156, 163, 175, 0.3);
  border-radius: 10px;
}
.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: rgba(156, 163, 175, 0.5);
}
</style>
